language: csharp
mono: none
dotnet: 2.1.200
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./scripts/build.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/deploy.sh; fi
branches:
  only:
  - master
before_deploy:
  - bash ./scripts/predeploy.sh
#deploy:
#  provider: releases
#  api_key:
#    secure: 1LKQ63NWNM4jgRxBzHHESZ+ultLP8O40uECwv3vAgb//9qlpw8q5NCshYp3qUFCneQP6iY6yo6x6eU7qweLmRcUjD8wqveuaizIeGZ41ItRd0wClOcqKXZxfhXAveZiDkS+lwIK2T9nGxJQscmXbe1zAx6T4F7d4tRF+FwyDg7m7foSmTNMKdWZJd1eY7Hte8J0VpfvYuZMCzhjdYFlhFzgE6cvxIP22BSuxts/dVXAogHWdWyughWUWme4xDAPWMgwLvrjnydpUryGFLAlnk+ImysNmFkiauXCSF6Mgcrq7WPSAgsjrUscBDHebnb8AMn/umbFEuVoqe/ZyZ3ENfiatMw6X54Xzh64UGqs/u3p7nM1HuFR4r/mZUoqDh7FyIG4PCu9molhgBGIBNaNq6tceQiekWhrS++L2AhRDhBCZ6hL5Xl2JbDw63fjCoFBNtHJGLIqlITac31smOG5+sCcK/shOGOP+41Q4CXbcL8xS+hendrX6JadHnz5MJCFnLVfLxFaEJl1bJupdbHY9QiGZJh4aXX5OtuxDm5vV4Rwepi0K+Vc9TTHgRKELlqZWU3Qp4B4ycbw+83rxbEnKDnGAUwQilRPZxBUMf9rjMOWn3HMuhc9t/Hlr2alUxlEQmGVS7UbgEl2Z4HvJ0HUH8RUvHAwK3ssITvHl+np5TAc=
#  file: "$TRAVIS_BUILD_DIR/releases/Stardew.MPSaveEditor-$TRAVIS_BUILD_ID.zip"
#  tag: "$(git describe --tags)"
#  on:
#    tag: true
